webtalk_init -webtalk_dir E:/Assignments_Work/Habib/Sem_3/DLD/Labs/Lab6_8/Lab6_8.sim/sim_1/behav/xsim/xsim.dir/testbench_v_counter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov  3 16:18:54 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7a93a5ba-3998-4c76-9ad5-c97fd9982374" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "08dd00a7f8ec4b8d8fa7d9f1b4cf88de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7680_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1643398323 -regid "" -xml E:/Assignments_Work/Habib/Sem_3/DLD/Labs/Lab6_8/Lab6_8.sim/sim_1/behav/xsim/xsim.dir/testbench_v_counter_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Assignments_Work/Habib/Sem_3/DLD/Labs/Lab6_8/Lab6_8.sim/sim_1/behav/xsim/xsim.dir/testbench_v_counter_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Assignments_Work/Habib/Sem_3/DLD/Labs/Lab6_8/Lab6_8.sim/sim_1/behav/xsim/xsim.dir/testbench_v_counter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
