build:
	gcc my_stack.c -o my_stack
	gcc dynamic_list.c -o dynamic_list

rebuild:
	gcc my_stack.c -o my_stack -DDEBUG
	gcc dynamic_list.c -o dynamic_list -DDEBUG

run:
	./my_stack
	./dynamic_list

clean:
	rm my_stack
	rm dynamic_list