build:
	gcc -o t1_a t1_a.c
	gcc -o t1_b t1_b.c
	gcc -o t1_c t1_c.c
	gcc -o t2_p1 t2_p1.c
	gcc -o t2_p2 t2_p2.c
	gcc -o t2_p3 t2_p3.c

run:
	./t1_a
	./t1_b
	./t1_c

clean:
	rm -rf t1_a t1_b t1_c t2_p1 t2_p2 t2_p3