build:
	@echo "Building..."
	gcc -lpthread -o t3 t3.c
	@echo "When you want to run, use: make run args='arg1 arg2 arg3 ...' where args are integers; the number of items being produced and consumed."

run:
	@echo "Running..."
	./t3 $(args)

clean:
	@echo "Cleaning..."
	rm -f t3