execl1:
	gcc -o l1 l1.c
	./l1

execl2:
	gcc -o l2 l2.clean4
	./l2

execl3:
	gcc -o l3 l3.c
	./l3

execmodl3:
	gcc -o modl3 mod_l3.c
	./modl3

clean:
	rm -f l1 l2 l3 modl3

build4:
	gcc -o q4 q4.c

run4:
	./q4

clean4:
	rm -f q4


build5:
	gcc -o q5 q5.c

run5:
	./q5

clean5:
	rm -f q5